In [22]:
import torch
import numpy as np
from scipy.spatial import distance_matrix

In [3]:
depot = torch.rand(size=(5, 1, 2))
nodes = torch.rand(size=(5, 10, 2))

In [15]:
depot_ = depot[0].numpy()
node = nodes[0].numpy()
nodes = np.concatenate([depot_, node], axis=0)
nodes

array([[0.9276323 , 0.04201007],
       [0.36034948, 0.23714733],
       [0.718716  , 0.3434391 ],
       [0.7497392 , 0.53622097],
       [0.04420394, 0.12459552],
       [0.6536341 , 0.08271015],
       [0.10470617, 0.45584416],
       [0.0101887 , 0.20923328],
       [0.16000587, 0.74691147],
       [0.10504794, 0.48394197],
       [0.67549205, 0.70996743]], dtype=float32)

In [40]:
batch_size = 5
problem_size = 10
depot_xy = torch.rand(size=(batch_size, 1, 2))
# shape: (batch, 1, 2)
node_xy = torch.rand(size=(batch_size, problem_size, 2))
# shape: (batch, problem, 2)
total_n = 1+problem_size
dm = np.zeros((batch_size, total_n, total_n))
for b in range(batch_size):
    depot = depot_xy[b].numpy()
    node = node_xy[b].numpy()
    nodes = np.concatenate([depot, node], axis=0)
    distance = distance_matrix(nodes,nodes)
    dm[b] = distance
dm_t = torch.from_numpy(dm)

In [114]:
pomo_size = 8
dm_total = dm_t[:, None, :, :].expand(batch_size, pomo_size, problem_size+1, problem_size+1)
print(dm_total[:,:,:,0][:3,:3,:3])
print('data matrixshape: ',dm_total.shape)
pre_index1 = torch.from_numpy(np.random.randint(1,5,size=(5,8)))
pre_index2 = pre_index1[:,:,None]
print('pre_index shape: ',pre_index2.shape)
distance_list = []
for i in range(problem_size+1):
    distance_list.append(dm_total[:,:,:,i].gather(dim=2,index=pre_index2).squeeze())
distance_list = torch.stack(distance_list,dim=2)
print('distance list shape: ',distance_list.shape)

tensor([[[0.0000, 0.6893, 0.4091],
         [0.0000, 0.6893, 0.4091],
         [0.0000, 0.6893, 0.4091]],

        [[0.0000, 0.1742, 0.6539],
         [0.0000, 0.1742, 0.6539],
         [0.0000, 0.1742, 0.6539]],

        [[0.0000, 0.9417, 0.8021],
         [0.0000, 0.9417, 0.8021],
         [0.0000, 0.9417, 0.8021]]], dtype=torch.float64)
data matrixshape:  torch.Size([5, 8, 11, 11])
pre_index shape:  torch.Size([5, 8, 1])
distance list shape:  torch.Size([5, 8, 11])


In [113]:
dm_total[:,:,:,0][:3,:3,:3]

tensor([[[0.0000, 0.6893, 0.4091],
         [0.0000, 0.6893, 0.4091],
         [0.0000, 0.6893, 0.4091]],

        [[0.0000, 0.1742, 0.6539],
         [0.0000, 0.1742, 0.6539],
         [0.0000, 0.1742, 0.6539]],

        [[0.0000, 0.9417, 0.8021],
         [0.0000, 0.9417, 0.8021],
         [0.0000, 0.9417, 0.8021]]], dtype=torch.float64)

In [118]:
from datetime import datetime
import pytz
datetime.now(pytz.timezone("US/Pacific"))

datetime.datetime(2022, 7, 18, 15, 36, 53, 97618, tzinfo=<DstTzInfo 'US/Pacific' PDT-1 day, 17:00:00 DST>)

In [121]:
torch.rand(size=(batch_size, 1, 2)).dtype

torch.float32

In [126]:
torch.from_numpy(np.array([[1,1.5,2]],dtype=np.float32)).dtype

torch.float32